<a href="https://colab.research.google.com/github/awaiskhan131931-ctrl/transformer/blob/main/transformer_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

**take a sample**

In [2]:
english = [
    "hello",
    "how are you",
    "i am fine",
    "what is your name",
    "my name is awais",
    "where are you going",
    "i am going to school",
    "do you like tea",
    "yes i like tea",
    "i love pakistan",
    "good morning",
    "good night",
    "see you later",
    "come here",
    "sit down",
    "open the door",
    "close the window",
    "what are you doing",
    "i am reading a book",
    "this is my friend",
    "i am hungry",
    "i am tired",
    "please help me",
    "how old are you",
    "i am twenty years old",
    "where do you live",
    "i live in swat",
    "what is this",
    "this is a computer",
    "i like programming",
    "tensorflow is powerful",
    "deep learning is interesting",
    "machine learning is the future",
    "the weather is very hot",
    "today is friday",
    "i want to learn ai",
    "can you teach me",
    "i have a laptop",
    "my laptop is hp",
    "the internet is slow",
    "i am watching a movie",
    "he is my brother",
    "she is my sister",
    "we are students",
    "they are playing cricket",
    "the baby is sleeping",
    "please give me water",
    "i need some food",
    "this car is very fast",
    "the cat is under the table"
]

poshto = [
    "<start> سلام <end>",
    "<start> ته څنګه يې <end>",
    "<start> زه ښه يم <end>",
    "<start> ستا نوم څه دی <end>",
    "<start> زما نوم اويس دی <end>",
    "<start> ته چېرته ځې <end>",
    "<start> زه ښوونځي ته ځم <end>",
    "<start> ته چای خوښوې <end>",
    "<start> هو زه چای خوښوم <end>",
    "<start> زه پاکستان سره مينه لرم <end>",
    "<start> سهار مو پخير <end>",
    "<start> شپه مو پخير <end>",
    "<start> بيا به سره ګورو <end>",
    "<start> دلته راشه <end>",
    "<start> کښېنه <end>",
    "<start> دروازه خلاصه کړه <end>",
    "<start> کړکۍ بنده کړه <end>",
    "<start> ته څه کوې <end>",
    "<start> زه کتاب لولم <end>",
    "<start> دا زما ملګری دی <end>",
    "<start> زه وږی يم <end>",
    "<start> زه ستړی يم <end>",
    "<start> مهرباني وکړه مرسته راسره وکړه <end>",
    "<start> ستا عمر څو کاله دی <end>",
    "<start> زما عمر شل کاله دی <end>",
    "<start> ته چېرته اوسېږې <end>",
    "<start> زه په سوات کې اوسېږم <end>",
    "<start> دا څه دي <end>",
    "<start> دا کمپيوټر دی <end>",
    "<start> زه پروګرامنګ خوښوم <end>",
    "<start> ټېنسرفلو ځواکمن دی <end>",
    "<start> ژوره زده کړه زړه پورې ده <end>",
    "<start> ماشين زده کړه راتلونکې ده <end>",
    "<start> هوا ډېره ګرمه ده <end>",
    "<start> نن جمعه ده <end>",
    "<start> زه مصنوعي ځيرکتيا زده کول غواړم <end>",
    "<start> ته ما ته زده کړه راکولی شې <end>",
    "<start> زما سره لپټاپ شته <end>",
    "<start> زما لپټاپ HP دی <end>",
    "<start> انټرنېټ ډېر ورو دی <end>",
    "<start> زه فلم ګورم <end>",
    "<start> هغه زما ورور دی <end>",
    "<start> هغه زما خور ده <end>",
    "<start> موږ زده کوونکي يو <end>",
    "<start> هغوی کرکټ لوبوي <end>",
    "<start> ماشوم ويده دی <end>",
    "<start> مهرباني وکړئ اوبه راکړئ <end>",
    "<start> زه خوراک ته اړتيا لرم <end>",
    "<start> دا موټر ډېر تېز دی <end>",
    "<start> پيشو د مېز لاندې ده <end>"
]

**tokenizaion**

In [3]:
eng_tokenizer = Tokenizer()
eng_tokenizer.fit_on_texts(english)

poshto_tokenizer = Tokenizer()
poshto_tokenizer.fit_on_texts(poshto)


print("English Tokenizer:")
print(eng_tokenizer.word_index)
print(eng_tokenizer.word_counts)
print(len(eng_tokenizer.word_index) + 1)


#====================

print("\nPoshto Tokenizer:")
print(poshto_tokenizer.word_index)
print(poshto_tokenizer.word_counts)
print(len(poshto_tokenizer.word_index) + 1)

English Tokenizer:
{'is': 1, 'i': 2, 'you': 3, 'the': 4, 'am': 5, 'are': 6, 'my': 7, 'a': 8, 'this': 9, 'what': 10, 'like': 11, 'me': 12, 'how': 13, 'name': 14, 'where': 15, 'going': 16, 'to': 17, 'do': 18, 'tea': 19, 'good': 20, 'please': 21, 'old': 22, 'live': 23, 'learning': 24, 'very': 25, 'laptop': 26, 'hello': 27, 'fine': 28, 'your': 29, 'awais': 30, 'school': 31, 'yes': 32, 'love': 33, 'pakistan': 34, 'morning': 35, 'night': 36, 'see': 37, 'later': 38, 'come': 39, 'here': 40, 'sit': 41, 'down': 42, 'open': 43, 'door': 44, 'close': 45, 'window': 46, 'doing': 47, 'reading': 48, 'book': 49, 'friend': 50, 'hungry': 51, 'tired': 52, 'help': 53, 'twenty': 54, 'years': 55, 'in': 56, 'swat': 57, 'computer': 58, 'programming': 59, 'tensorflow': 60, 'powerful': 61, 'deep': 62, 'interesting': 63, 'machine': 64, 'future': 65, 'weather': 66, 'hot': 67, 'today': 68, 'friday': 69, 'want': 70, 'learn': 71, 'ai': 72, 'can': 73, 'teach': 74, 'have': 75, 'hp': 76, 'internet': 77, 'slow': 78, 'watc

**Convert Text → Sequences + Padding**

In [4]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
eng_sequence = eng_tokenizer.texts_to_sequences(english)
poshto_sequence = poshto_tokenizer.texts_to_sequences(poshto)

eng_padded = pad_sequences(eng_sequence, padding="post")
poshto_padded = pad_sequences(poshto_sequence, padding='post')


**Embedding Layer**


In [5]:
from tensorflow.keras.layers import Embedding
print(len(eng_tokenizer.word_index) + 1)
Embedding_layer = Embedding(input_dim = len(eng_tokenizer.word_index)+1 ,output_dim=64)

embedded_output = Embedding_layer(eng_padded)

print(f'embedding shape :\n {embedded_output.shape}')
print(f'first embeddedd sentence :\n {embedded_output[0]}')

102
embedding shape :
 (50, 6, 64)
first embeddedd sentence :
 [[ 0.01383634  0.03804654  0.02283615  0.01063994  0.00472999 -0.04725983
  -0.04348999  0.00339831 -0.02736002  0.00123332 -0.01949601  0.04819516
   0.04144384 -0.00391544  0.04981991 -0.04364978 -0.01794367 -0.02728418
  -0.00111115  0.01372698 -0.02199384 -0.00442664 -0.03041412  0.03547386
  -0.03922904  0.0297822  -0.01786188 -0.00753961  0.0132985  -0.02597173
   0.01210167  0.02658231 -0.02074286 -0.04318491  0.01460021 -0.03646296
   0.00349934 -0.02587038  0.04095883  0.04684413  0.04546456 -0.03130182
  -0.00347413 -0.02915425  0.0462261   0.01564792 -0.01495407  0.0480556
   0.02575776  0.01398798 -0.00308366  0.03933909  0.03911289  0.04795847
   0.03585755 -0.00197669 -0.01380922  0.04490722  0.01394304 -0.00057669
  -0.01852775  0.02092167 -0.02023689  0.04392225]
 [ 0.04597234 -0.04783732  0.00245555 -0.03812744 -0.02301517  0.00146927
  -0.00373507  0.03284407 -0.02795389  0.02234207 -0.04595058 -0.00322258

**Positional Encoding**

Transformers process all words together, so they do NOT naturally know word order.

In [6]:
import numpy as np
import tensorflow as tf # Added tensorflow import

def positional_encoding_function(position, d_model):
    # Create an array for positions (0 to position-1)
    pos = np.arange(position)[:, np.newaxis] # shape: (position, 1)
    div_term = 1 / np.power(10000, np.arange(0, d_model, 2) / np.float32(d_model)) # Shape (d_model/2,)

    angle_rads = pos * div_term
    pos_encoding_matrix = np.zeros((position, d_model))
    pos_encoding_matrix[:, 0::2] = np.sin(angle_rads)
    pos_encoding_matrix[:, 1::2] = np.cos(angle_rads)

    pos_encoding = pos_encoding_matrix[np.newaxis, ...]

    return tf.cast(pos_encoding, dtype=tf.float32)


# Create positional encoding

# Corrected function call name
pos_encoding = positional_encoding_function(
    position=eng_padded.shape[1],
    d_model=64
)

print("Positional Encoding Shape:")
print(pos_encoding.shape)

transfomer_output = embedded_output + pos_encoding

print("Transformer Output Shape:")
print(transfomer_output.shape)

Positional Encoding Shape:
(1, 6, 64)
Transformer Output Shape:
(50, 6, 64)


**Build Multi-Head Attention Layer**

In [7]:
from tensorflow.keras.layers import MultiHeadAttention, LayerNormalization
MultiHeadAttention = MultiHeadAttention(num_heads=4, key_dim=64)

attention_layer_output = MultiHeadAttention(
    query=transfomer_output,
    key=transfomer_output,
    value=transfomer_output
)

print("Attention Layer Output Shape:")
print(attention_layer_output.shape)

Attention Layer Output Shape:
(50, 6, 64)


**ADD & NORM (Residual Connection + Layer Normalization)**

In [8]:
add_output = transfomer_output + attention_layer_output

print("Add & Norm Output Shape:")

layers_normaliztion = LayerNormalization()
norm_output = layers_normaliztion(add_output)

print(norm_output.shape)

Add & Norm Output Shape:
(50, 6, 64)


**Feed Forward Network (FFN)**

In [9]:
from tensorflow.keras.layers import Dense

# Feed Forward Network

ffn = tf.keras.Sequential(
    [
        Dense(256, activation='relu'),
        Dense(64)
    ]
)
ffn_output = ffn(norm_output)

print("FFN Output Shape:")
print(ffn_output.shape)

FFN Output Shape:
(50, 6, 64)


**ADD & NORM after FFN**

In [10]:
add_output_2 = norm_output + ffn_output

print("Add & Norm Output Shape:")

layers_normaliztion_2 = LayerNormalization()
encoder_last_output = layers_normaliztion_2(add_output_2)

print(encoder_last_output.shape)

Add & Norm Output Shape:
(50, 6, 64)


the above cell is the last cell of encodding now we start data prefocessing for decodder


**Decoder Input and Target**

In [11]:
decoder_input = poshto_padded[:,:-1]
decoder_target = poshto_padded[:,1:]

print("Decoder Input Shape:")
print(decoder_input)

print(f'decoder target :\n {decoder_target}')


Decoder Input Shape:
[[  1  29   2   0   0   0   0   0]
 [  1   5  30  31   2   0   0   0]
 [  1   3  32  11   2   0   0   0]
 [  1  14  15  12   4   2   0   0]
 [  1   6  15  33   4   2   0   0]
 [  1   5  16  34   2   0   0   0]
 [  1   3  35   5  36   2   0   0]
 [  1   5  17  37   2   0   0   0]
 [  1  38   3  17  18   2   0   0]
 [  1   3  39  13  40  19   2   0]
 [  1  41  20  21   2   0   0   0]
 [  1  42  20  21   2   0   0   0]
 [  1  43  44  13  45   2   0   0]
 [  1  46  47   2   0   0   0   0]
 [  1  48   2   0   0   0   0   0]
 [  1  49  50   8   2   0   0   0]
 [  1  51  52   8   2   0   0   0]
 [  1   5  12  53   2   0   0   0]
 [  1   3  54  55   2   0   0   0]
 [  1  10   6  56   4   2   0   0]
 [  1   3  57  11   2   0   0   0]
 [  1   3  58  11   2   0   0   0]
 [  1  22  23  59  60  23   2   0]
 [  1  14  24  61  25   4   2   0]
 [  1   6  24  62  25   4   2   0]
 [  1   5  16  63   2   0   0   0]
 [  1   3  64  65  66  67   2   0]
 [  1  10  12  68   2   0   0   0]

**decoder Embedding** (poshto Embedding)


In [12]:
from tensorflow.keras.layers import Embedding

decoder_embedding = Embedding(input_dim=len(poshto_tokenizer.word_index)+1, output_dim=64)

decoder_embedded_output = decoder_embedding(decoder_input)

print(f'decoder embedding shapre : \n {decoder_embedded_output.shape}')
print(f'first decoder embedded sentence :\n {decoder_embedded_output[0]}')

decoder embedding shapre : 
 (50, 8, 64)
first decoder embedded sentence :
 [[ 4.49497215e-02 -4.32339311e-02  2.58018821e-03 -2.60864142e-02
  -3.18091400e-02 -4.68101352e-03 -4.70051654e-02 -3.38377245e-02
   2.39870287e-02 -3.49673256e-02  8.72344896e-03 -2.78451797e-02
  -6.26579672e-03  3.54210623e-02 -3.75211127e-02 -1.85442083e-02
  -4.90486287e-02  3.63166444e-02  3.33057083e-02  8.04662704e-05
   1.12511627e-02  1.30225345e-03  1.02035888e-02  3.12798657e-02
   2.25887932e-02 -4.51547764e-02 -7.62649626e-03 -2.12908275e-02
   2.91315056e-02  1.06411055e-03 -3.37856784e-02 -1.94592476e-02
  -1.04069598e-02 -1.10423192e-02 -9.84323025e-03 -1.63294673e-02
   1.64974071e-02  1.58701576e-02 -3.38802487e-03 -1.82026140e-02
   1.16091967e-02 -4.88812216e-02  2.71467008e-02 -2.51973793e-03
   2.39949934e-02 -3.39153185e-02 -4.89353053e-02  2.38399766e-02
  -4.23820615e-02 -4.50821780e-02 -4.06157486e-02 -2.47914325e-02
   2.78985500e-03 -4.50700186e-02 -8.26667622e-03  2.48363055e-02


**positional Endcodding**

In [13]:
decoder_positional_encoding = positional_encoding_function(position=decoder_embedded_output.shape[1], d_model=64)


#this is new shape of encodded data
decoder_transformer_input = decoder_embedded_output + decoder_positional_encoding

print("Decoder Positional Encoding Shape:")
print(decoder_positional_encoding.shape)

Decoder Positional Encoding Shape:
(1, 8, 64)


**MASKED MULTI-HEAD ATTENTION**


In [19]:


seq_len = decoder_transformer_input.shape[1]
look_ahead_mask = 1 - tf.linalg.band_part(tf.ones((seq_len, seq_len)), -1, 0)


masked_attention_layer = tf.keras.layers.MultiHeadAttention(
    num_heads=4,
    key_dim=64
)

masked_attention_output = masked_attention_layer(
    query=decoder_transformer_input,
    value=decoder_transformer_input,
    key=decoder_transformer_input,
    attention_mask=look_ahead_mask
)

print("Masked Attention Output Shape:")
print(masked_attention_output.shape)



Masked Attention Output Shape:
(50, 8, 64)


**Decoder Add & Norm**


In [21]:
add_output_3 = decoder_transformer_input + masked_attention_output
print("Add & Norm Output Shape:")

decoder_layers_normaliztion_3 = LayerNormalization()
encoder_last_output_3 = decoder_layers_normaliztion_3(add_output_2)

print(encoder_last_output_3.shape)

Add & Norm Output Shape:
(50, 6, 64)
